### ISSUE TITLE
Consider the Boost Software License?

### ISSUE THREAD

**Issue by vinniefalco** [hrantzsch/keychain#13]
Would you consider re-releasing this under the Boost Software License?

**Comment by vslavik** [comment]
(Commenting as not-the-repo-owner)

This can be tricky. At [first](https://web.archive.org/web/20150106221458/http://ideas.opensource.org/ticket/45) [reading](https://softwareengineering.stackexchange.com/questions/44076/whats-the-fundamental-difference-between-the-mit-and-the-boost-open-source-lice) of the [differences](https://law.stackexchange.com/questions/91/is-there-any-difference-in-meaning-between-the-boost-and-mit-software-licenses), the Boost license is *not* a strict superset of MIT (in particular, it loosens requirements of MIT in terms of license copies in binaries) and so one can't just hand-wave over it and relicense.

For the record, as the copyright owner of some of the code this repo is derived from (appreciate the prominent credit, btw), I would have no problem with it. But my work was *also* derivative from https://github.com/atom/node-keytar by GitHub and that's where the bulk of the original code is from.

**Comment by hrantzsch** [comment]
Thanks @vslavik for the insights and thanks for the code we reused :)

TBH I don't know that much about licensing law, but I'll read up a bit on occasion. If it turns out to be simple, I don't mind changing the license at all. It seems to be easy [to change from MIT to GPL](https://opensource.stackexchange.com/questions/5832/relicensing-an-mit-licensed-project-under-the-gpl-that-has-non-code-contribution/5833#5833), but I guess GLP _is_ a strict superset of MIT then?

**Comment by vinniefalco** [comment]
> in particular, it loosens requirements of MIT in terms of license copies in binaries

Yes that's right, it is the primary difference.

**Comment by hrantzsch** [comment]
After what I've read so far, we'd need the permission of all copyright holders to change the license -- exactly like @vslavik pointed out. I'm not interested in trying to get that, to be honest.

@vinniefalco do you have any different information regarding that? Otherwise I guess we'll stay with MIT.

**Comment by vinniefalco** [comment]
Well, thank you for considering it !
